excluded:
  - .build
  - .swiftpm
  - Examples

opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - redundant_type_annotation
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

disabled_rules:
  - todo

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length: 2
  excluded:
    - id
